apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Values.Namespacename }}
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: 300m
      memory: 512Mi
    min:
      cpu: 100m
      memory: 100Mi
