apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-name
  namespace: {{ .Values.Namespacename }}
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 2Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    pods: '4'