apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    {{- toYaml .Values.selector | nindent 4 }}
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP