apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appbackend-helm
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: app-backend
  project: appbackend-helm
  source:
    helm:
      valueFiles:
        - values.yaml
    path: helm
    repoURL: 'https://github.com/cristhiancaldas/argocd-helm.git'
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2