apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appbackend-helm
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: This is just an example.
  destinations:
    - name: in-cluster
      namespace: app-backend
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/cristhiancaldas/argocd-helm.git'
status: {}