apiVersion: v1
kind: Secret
metadata:
  name: github.com-tcristhian-caldas
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/cristhiancaldas/argocd-helm.git
